root: true

env:
  node: true

parser: "@typescript-eslint/parser"

parserOptions:
  project:
    - "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

rules:
  "@typescript-eslint/no-inferrable-types": "off"
  "@typescript-eslint/no-non-null-assertion": "off"
  simple-import-sort/exports: error
  simple-import-sort/imports:
    - error
    - groups:
        - ["\\u0000$"] # Types
        - ["^\\u0000"] # Side-effects
        - ["^@?\\w"] # Packages
        - ["^"] # All other packages
        - ["^\\."] # Relative imports

overrides:
  - files: ["**/__tests__/**/*.ts"]
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    rules:
      jest/expect-expect:
        - "error"
        - assertFunctionNames:
            - expect
            - n.done
