name: Publish Documentation

on:
  push:
    branches: [master]

jobs:
  deploydoc:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci

      - id: branch
        name: Extract branch
        shell: bash
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Update dochome
        uses: actions/github-script@v3
        env:
          VERSION: ${{ steps.branch.outputs.short_ref }}
        with:
          script: |
            const fs = require("fs");
            const path = require("path");

            const root = process.env.GITHUB_WORKSPACE;
            const dochomePth = path.join(root, "dochome.md");
            const template = fs.readFileSync(dochomePth, { encoding: "utf-8" });
            const dochome = template.replace(/{{version}}/g, process.env.VERSION);
            fs.writeFileSync(dochomePth, dochome);

      - run: npm run gendoc

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
          commit-message: Deploy docs for branch ${{ steps.branch.outputs.short_ref }}
          target-folder: docs/${{ steps.branch.outputs.short_ref }}
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: true
